#!/usr/bin/env php
<?php declare(strict_types=1);

use Conso\Conso;
use Conso\Input;
use Conso\Output;

require 'vendor/autoload.php';



try {
    error_reporting(0);
    $conso = new Conso(new Input, new Output);
    error_reporting(-1);

    // Error logging
    ini_set('log_errors', '1');
    ini_set('error_log', './php_errors.log');


    // include your commands
    require_once 'src/commands.php';

    // Set Metadata for Conso to use
    $conso->setName('Made-Up Word Generator');
    $conso->setVersion('0.0.1');
    $conso->setAuthor('Ian Maurmann');


    // Set Signature in Conso
    $signature =
        "\n"
        . '──────────────────────' . "\n"
        . 'Made-Up Word Generator' . "\n"
        . '──────────────────────' . "\n"
    ;
    $conso->setSignature($signature);

    // Run Conso
    $conso->run();
} catch (Exception $e) {
    throw $e;
}